### ISSUE TITLE
Upgrade to Python3

### ISSUE THREAD

**Issue by jakobkogler** [nooodl/gs2#14]
@nooodl Are there any plans on upgrading to Python3?

I started a private project yesterday where I needed the gs2-module. I realized too late, that gs2 only runs with Python2. So I started porting it to Python3 (https://github.com/jakobkogler/gs2/tree/python3). So far I can run the example from the Readme on Linux. I guess most of the functionality works, but I didn't make any tests yet. 

So my question, do you want to upgrade? If so, I'll do some more testing, fix the remaining bugs (I'm certain that there are some), clean up the code a little bit (QuantifiedCode give quite a bad rating) and make a pull request.

**Comment by maurisvh** [comment]
Hi Jakob! (I have two github accounts. It's a long story.)

Upgrading to Python 3 actually sounds good -- as a matter of fact, since I started working on gs2, I've pretty much shifted to exclusively using Python 3 for scripts and small projects!

I've been busy with work/school, but I'm very grateful that you've gone through the effort of porting it. If you finish it, I will help run more tests. You have my go-ahead!

You can find lots of gs2 code [here](http://golf.shinh.org/l.rb?gs2): for problems marked "(post mortem)", click on the problem name to see input/output, and the user names to see the solutions. (Most of it should still work, but there have been slight changes/fixes to the language compared to the version on shinh's server. Just make sure anything that works on the version you forked from works on the new one, I guess.)
